#!/usr/bin/env python3
"""Embed webui/ into one gzipped PROGMEM blob for GET /.

Usage, from the repository root:

    python3 tools/embed_webui.py

Reads webui/index.html, webui/app.css and webui/app.js, inlines the stylesheet
and the script into the HTML (leaving zero external references), gzips the
result deterministically and writes esp32_marauder/webui_data.h.
WebControl.cpp serves that blob as GET / with "Content-Encoding: gzip".

The output is byte-identical for identical inputs (gzip mtime pinned to 0, no
timestamps, fixed byte layout), so re-running the generator in CI never churns
the header.
"""

from __future__ import annotations

import gzip
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
WEBUI_DIR = ROOT / "webui"
OUT_HEADER = ROOT / "esp32_marauder" / "webui_data.h"

# Flash budget for the gzipped page (24 KiB).
GZIP_BUDGET = 24576

# Bytes per line in the emitted array; purely cosmetic but fixed for
# deterministic output.
BYTES_PER_LINE = 16

# The real tags in webui/index.html:  <link rel="stylesheet" href="app.css">
# and  <script src="app.js"></script>.  Attribute order/fill is tolerated, but
# each must occur exactly once.
CSS_LINK = re.compile(r"""<link\b[^>]*\bhref=["'](?:\./)?app\.css["'][^>]*>""")
JS_TAG = re.compile(
    r"""<script\b[^>]*\bsrc=["'](?:\./)?app\.js["'][^>]*>\s*</script\s*>"""
)

# Anything that would make the device fetch a file it does not serve. After
# inlining this must never match.
EXT_REF = re.compile(r"""(?:href|src)=["'](?:\./)?app\.(?:css|js)["']""")

# Absolute URLs anywhere in the page. xmlns= declarations and data: URIs are
# not fetches, so they are reported as warnings only (see is_xmlns()).
ABS_URL = re.compile(r"""https?://[^\s"'<>)]+""")


def is_xmlns(text: str, start: int) -> bool:
    """True when the URL at `start` is an xmlns='...' declaration.

    `xmlns='` is seven characters, so the URL only has to sit directly after
    one of those two quote forms — everything else is reported.
    """
    return text[max(0, start - 7) : start] in ("xmlns='", 'xmlns="')


class EmbedError(Exception):
    """A webui/ input the generator cannot safely embed."""


def inline(html: str, css: str, js: str) -> str:
    """Replace the stylesheet link and the script tag with inlined blocks."""
    links = CSS_LINK.findall(html)
    scripts = JS_TAG.findall(html)
    if len(links) != 1:
        raise EmbedError(
            'embed_webui: expected exactly one <link href="app.css"> tag, '
            f"found {len(links)}"
        )
    if len(scripts) != 1:
        raise EmbedError(
            'embed_webui: expected exactly one <script src="app.js"> tag, '
            f"found {len(scripts)}"
        )

    html = CSS_LINK.sub(lambda _m: "<style>" + css + "</style>", html, count=1)
    html = JS_TAG.sub(lambda _m: "<script>" + js + "</script>", html, count=1)

    if EXT_REF.search(html):
        raise EmbedError(
            "embed_webui: an app.css/app.js reference survived inlining; "
            "the device serves a single document and cannot fetch it"
        )
    return html


def warn_about_absolute_urls(text: str) -> None:
    for match in ABS_URL.finditer(text):
        if is_xmlns(text, match.start()):
            continue
        line = text.count("\n", 0, match.start()) + 1
        print(
            f"embed_webui: warning: absolute URL at line {line}: {match.group(0)}",
            file=sys.stderr,
        )


def render_header(gzip_blob: bytes) -> str:
    """Render the generated header. Deterministic for a given blob."""
    rows = []
    for offset in range(0, len(gzip_blob), BYTES_PER_LINE):
        chunk = gzip_blob[offset : offset + BYTES_PER_LINE]
        rows.append("  " + ", ".join(f"0x{byte:02x}" for byte in chunk) + ",")
    # Drop the trailing comma on the last row: valid either way, but dropping
    # it keeps the layout stable if the size ever shrinks to one row.
    if rows:
        rows[-1] = rows[-1].rstrip(",")

    return (
        "// Generated by tools/embed_webui.py — DO NOT EDIT.\n"
        "// Source: webui/index.html + webui/app.css + webui/app.js, inlined into\n"
        "// one document and gzipped (level 9, mtime 0). Re-run the generator after\n"
        "// any webui/ change:  python3 tools/embed_webui.py\n"
        "#ifndef WEBUI_DATA_H\n"
        "#define WEBUI_DATA_H\n"
        "\n"
        "#include <Arduino.h>\n"
        "\n"
        "// gzip-compressed HTML, served as GET / with Content-Encoding: gzip.\n"
        "static const uint8_t WEBUI_HTML_GZ[] PROGMEM = {\n"
        + "\n".join(rows)
        + "\n};\n"
        "\n"
        f"static const size_t WEBUI_HTML_GZ_LEN = {len(gzip_blob)};\n"
        "\n"
        "#endif  // WEBUI_DATA_H\n"
    )


def main() -> int:
    try:
        html_bytes = (WEBUI_DIR / "index.html").read_bytes()
        css_bytes = (WEBUI_DIR / "app.css").read_bytes()
        js_bytes = (WEBUI_DIR / "app.js").read_bytes()
    except OSError as error:
        print(f"embed_webui: cannot read webui/: {error}", file=sys.stderr)
        return 1

    try:
        html = html_bytes.decode("utf-8")
        css = css_bytes.decode("utf-8")
        js = js_bytes.decode("utf-8")
    except UnicodeDecodeError as error:
        print(f"embed_webui: webui/ is not UTF-8: {error}", file=sys.stderr)
        return 1

    raw_size = len(html_bytes) + len(css_bytes) + len(js_bytes)

    try:
        document = inline(html, css, js)
    except EmbedError as error:
        print(str(error), file=sys.stderr)
        return 1
    warn_about_absolute_urls(document)

    document_bytes = document.encode("utf-8")
    # mtime=0 pins the gzip header timestamp; compresslevel=9 is fixed. Both
    # are what make re-runs byte-identical.
    gzip_blob = gzip.compress(document_bytes, 9, mtime=0)

    if len(gzip_blob) > GZIP_BUDGET:
        print(
            f"embed_webui: gzip size {len(gzip_blob)} B exceeds the "
            f"{GZIP_BUDGET} B budget — trim webui/ before embedding",
            file=sys.stderr,
        )
        return 1

    try:
        OUT_HEADER.parent.mkdir(parents=True, exist_ok=True)
        OUT_HEADER.write_bytes(render_header(gzip_blob).encode("utf-8"))
    except OSError as error:
        print(f"embed_webui: cannot write {OUT_HEADER}: {error}", file=sys.stderr)
        return 1

    sizes = (
        f"index.html {len(html_bytes)} B"
        f" + app.css {len(css_bytes)} B"
        f" + app.js {len(js_bytes)} B"
    )
    print(f"embed_webui: raw     {raw_size} B ({sizes})")
    print(f"embed_webui: inlined {len(document_bytes)} B (self-contained)")
    print(
        f"embed_webui: gzip    {len(gzip_blob)} B <= {GZIP_BUDGET} B budget "
        f"({GZIP_BUDGET - len(gzip_blob)} B headroom)"
    )
    print(f"embed_webui: wrote {OUT_HEADER.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
