#pragma once

#ifndef WebControl_h
#define WebControl_h

#include "configs.h"

#include "ESPAsyncWebServer.h"

// P1 of the web-control architecture. The server is deliberately bound to
// 8080: the Evil Portal owns the global `AsyncWebServer server(80)` and its
// catch-all handler must never be touched by this module.
#define WEBUI_PORT 8080

// Persisted bool setting ("WebUI") — single source of truth for auto-start.
#define WEBUI_SETTING_KEY "WebUI"

// start() modes
#define WEBUI_MODE_AP  0  // bring up an open SoftAP (Marauder-XXXX), then serve
#define WEBUI_MODE_STA 1  // serve on the WiFi interface that already exists

// Heap guards. MEM_LOWER_LIM comes from configs.h; webui must never prevent a
// clean boot, and handlers must shed load instead of OOMing the async_tcp task.
#define WEBUI_START_HEAP_MARGIN (64UL * 1024UL)
#define WEBUI_LOW_HEAP_MARGIN   (16UL * 1024UL)

// Stage 2 quiet-drain: the teardown only runs after WEBUI_DRAIN_MS with
// in_flight == 0 observed on EVERY loop pass (the deadline is reset while
// anything is in flight), so this is a quiet period, not a since-stop timer.
// It must outlast the library's 3 s client rx-timeout, so a connection that
// goes quiet mid-request disconnects inside the window instead of still
// being open when the arenas are freed.
#define WEBUI_DRAIN_MS 5000

// P3: fixed-size marshaled CLI command slot (127 chars + NUL). Commands longer
// than this are rejected with 400 BAD_PARAM instead of being truncated.
#define WEBUI_CLI_MAX 128

// P3: interface-recovery monitor throttle — at most one WiFi recovery check
// every 2 s, so a scan/recon that toggles the radio cannot cause a thrash.
#define WEBUI_IFACE_CHECK_MS 2000

// P4: size of one list-snapshot arena (two of them, PSRAM). Worst-case body
// is the AP page: 50 entries x 160 B (95 B fixed + 64 B escaped SSID) + a
// ~95 B envelope = ~8.1 KB, so 6 KB would truncate — 8 KB holds a full page.
#define WEBUI_SNAP_BUF_SIZE 8192

// P4: list pagination. limit defaults to 20 and is hard-capped at 50 so a
// single loop-task build stays bounded; a bigger limit is 400 BAD_PARAM.
#define WEBUI_LIST_LIMIT_DEFAULT 20
#define WEBUI_LIST_LIMIT_MAX     50

// P4: how long a published snapshot stays servable before the handler asks
// the loop task for a fresh one (the UI polls, so a rebuild follows at once).
#define WEBUI_SNAP_FRESH_MS 2000

// P4: bytes held back while building, so the envelope tail ("]}}") always
// fits. It is also larger than the biggest single entry (160 B), so an entry
// can never be cut in half by the bound check that uses it.
#define WEBUI_SNAP_ENTRY_ROOM 256

class WebControl {
  public:
    void setup();
    bool start(uint8_t mode);
    void stop();
    void status();
    void main();

  private:
    // In-flight tracking: called on the first line of every route handler so
    // stage 2 can wait until no handler is executing before freeing the two
    // snapshot arenas. The server object itself is never deleted (see main()).
    void trackReq(AsyncWebServerRequest* request);
    // Sends 503 {"code":"STOPPING"}/{"code":"LOW_HEAP"} (full error envelope)
    // and returns true when the caller must not continue handling the request.
    bool shedRequest(AsyncWebServerRequest* request, const char* command);
    // Shared JSON error/success envelopes: {"protocol":1,"command":...,...}.
    void sendError(AsyncWebServerRequest* request, const char* command,
                   const char* code, int http_code);
    void sendAccepted(AsyncWebServerRequest* request, const char* command);

    void handleInfo(AsyncWebServerRequest* request);
    void handleStatus(AsyncWebServerRequest* request);
    void handleScan(AsyncWebServerRequest* request);
    void handleRecon(AsyncWebServerRequest* request);
    void handleCli(AsyncWebServerRequest* request);
    // P5: GET / and GET /index.html serve the embedded, gzipped dashboard
    // (webui_data.h, generated by tools/embed_webui.py).
    void handleRoot(AsyncWebServerRequest* request);
    void handleNotFound(AsyncWebServerRequest* request);

    // P4 list endpoints. All list iteration happens in the loop task; these
    // handlers only replay a finished snapshot arena or queue the query.
    enum ListKind : uint8_t { LIST_APS = 0, LIST_STATIONS = 1, LIST_SSIDS = 2 };

    void handleList(AsyncWebServerRequest* request, ListKind kind,
                    const char* command);
    void handleCmd(AsyncWebServerRequest* request);
    // Parses offset/limit. Missing params keep their defaults (never an
    // error); anything non-numeric, negative, or above the cap is 400.
    bool parseListQuery(AsyncWebServerRequest* request, const char* command,
                        uint16_t& offset, uint16_t& limit);
    // True when the response (200 replay or 503 LOW_HEAP) was already sent.
    bool tryServeSnapshot(AsyncWebServerRequest* request, const char* command,
                          ListKind kind, uint16_t offset, uint16_t limit);
    void queueSnapshot(ListKind kind, uint16_t offset, uint16_t limit);
    // Shared P3 CLI-slot claim so /api/v1/cli and the P4 /api/v1/cmd alias
    // bound and marshal through the exact same 128-byte slot (the library has
    // already URL-decoded the value — no second decode happens here).
    void claimCliSlot(AsyncWebServerRequest* request, const char* command,
                      const String& raw);

    // P3 marshaling: route handlers (async_tcp task) publish exactly one
    // pending action into this slot; main() (loop task) consumes it. The
    // pending_set flag is the hand-off: the producer fills the fields first
    // and only then raises the flag, the consumer copies the fields out and
    // only then lowers it, so the two tasks never touch the payload at the
    // same time. A second request while the slot is full gets 503 BUSY.
    struct PendingAction {
      enum Kind : uint8_t {
        PEND_NONE = 0,
        PEND_SCAN_ON,     // StartScan(WIFI_SCAN_AP_STA)
        PEND_SCAN_OFF,    // StartScan(WIFI_SCAN_OFF)
        PEND_RECON_WIFI,  // recon_obj.start(ReconMode::WIFI_RECON)
        PEND_RECON_BLE,   // recon_obj.start(ReconMode::BLE_RECON)
        PEND_RECON_STOP,  // recon_obj.stop() + StartScan(WIFI_SCAN_OFF)
        PEND_CLI          // cli_obj.runCommand(String(cmd))
      };
      volatile uint8_t kind = PEND_NONE;
      volatile uint8_t arg = 0;
      // Loop-task-only read, and only while pending_set is raised. `volatile`
      // merely stops the compiler from eliding the fill; the cross-task
      // ordering is the module's explicit barrier standard: every producer
      // issues __sync_synchronize() after filling and before raising
      // pending_set, and consumePending() issues one after observing the flag
      // and before reading the payload.
      volatile char cmd[WEBUI_CLI_MAX] = {0};
    };

    // Loop-task side of P3: consumes the slot and the recovery monitor.
    void consumePending();
    void monitorIface();
    void recoverIface();

    // P4 loop-task side: builds one queued query into the NON-published arena
    // and publishes it. Called only from main(), so builds are serialized.
    bool buildSnapshot();
    bool buildAps(char* dst, size_t cap, size_t* len,
                  uint16_t offset, uint16_t limit);
    bool buildStations(char* dst, size_t cap, size_t* len,
                       uint16_t offset, uint16_t limit);
    bool buildSsids(char* dst, size_t cap, size_t* len,
                    uint16_t offset, uint16_t limit);

    // Loop-task only: caches IP/mode/mac so route handlers never call WiFi.
    void refreshNetCache();
    // Brings the SoftAP up (mode -> softAPConfig -> softAP). Does not touch
    // owns_ap — the caller decides whether it now owns the interface.
    bool initSoftAP();
    const char* modeName() const;
    void persistSetting(bool enabled);
    bool portalOwnsWifi();

    // Allocated on the first start() and NEVER deleted (oracle review
    // HIGH-1): stage 2 frees only the snapshot arenas, and a later start()
    // re-begin()s this same object with its routes already registered.
    AsyncWebServer* server = nullptr;

    // Read by handlers from the async_tcp task.
    // Signed on purpose: stage 2's quiet gate tests `in_flight == 0`, so a
    // stray extra decrement that parked the counter below 0 could only block
    // the teardown, never open it early (an unsigned counter would wrap to a
    // huge value instead — also blocking, but for the wrong reason).
    volatile int in_flight = 0;
    volatile bool running = false;
    volatile bool stopping = false;

    // P3 pending-action slot (written by handlers, consumed by main()).
    PendingAction pending;
    volatile bool pending_set = false;

    // P4 double-buffered list snapshot. The arenas are allocated on the
    // first start() and freed only by the stage-2 teardown in main() (which
    // runs only after a quiet drain, i.e. no handler inside
    // tryServeSnapshot()). publish_idx is the arena the async_tcp task may
    // read; the loop task only ever writes 1 - publish_idx, and publish_idx
    // is updated last.
    char* snap_buf[2] = {nullptr, nullptr};
    volatile int publish_idx = -1;     // -1 = nothing published yet
    // Query hand-off, handler -> loop task: the fields are only written while
    // snap_want is down, and only read while it is up (same pattern as
    // `pending`), so a build never observes a torn query.
    volatile bool snap_want = false;
    volatile ListKind snap_kind = LIST_APS;
    volatile uint16_t snap_offset = 0;
    volatile uint16_t snap_limit = WEBUI_LIST_LIMIT_DEFAULT;
    volatile uint32_t snap_req_seq = 0;  // queued builds; see queueSnapshot()
    // Metadata of a published arena, DOUBLE-BUFFERED BY ARENA INDEX exactly
    // like snap_buf[2] (oracle review HIGH-2: with single-slot metadata a
    // reader could pair arena generation N's bytes with the other
    // generation's kind/offset/limit/len/seq — spurious 503s, or a 200 at the
    // wrong offset when lengths coincided). Protocol: the loop task fills
    // pub_meta[target] completely and then release-stores
    // publish_idx = target; a handler loads publish_idx ONCE (H1) and reads
    // only pub_meta[idx]. No slot initializer is needed: a slot is only ever
    // read through an index the writer already stored, and start() drops
    // publish_idx back to -1 whenever the arenas are rebuilt.
    struct PubMeta {
      ListKind kind;
      uint16_t offset;
      uint16_t limit;
      uint16_t len;
      uint32_t seq;
      uint32_t built_ms;
    };
    volatile PubMeta pub_meta[2];
    // Raised by a handler for as long as it reads a published arena. One flag
    // is enough: every handler runs in the single async_tcp task, and the
    // builder tests it between reading publish_idx and choosing its arena
    // (the L1/L3 ordering documented in buildSnapshot()).
    volatile bool snap_reading = false;

    // Loop-task state.
    bool owns_ap = false;
    uint8_t start_mode = WEBUI_MODE_AP;
    uint32_t end_time = 0;
    uint32_t last_cache_refresh = 0;

    // P3 interface-recovery monitor state (loop task only).
    bool last_scanning = false;
    bool iface_edge = false;
    uint32_t last_iface_check = 0;

    // Cached network facts (written in the loop task, read by handlers).
    volatile uint32_t ip_addr = 0;   // host-order IPv4: a<<24 | b<<16 | c<<8 | d
    volatile uint8_t wifi_mode = 0;  // wifi_mode_t
    uint8_t mac6[6] = {0, 0, 0, 0, 0, 0};
};

#endif
